[package]
name = "coffee-ops-core"
description = "CoffeeOps core application logic"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
derive_more = { workspace = true, features = ["as_ref"] }
icu_normalizer = {workspace = true}
rootcause = {workspace = true}
uuid = {workspace = true, features = ["serde", "v7"]}
