[package]
name = "coffee-ops-db"
description = "CoffeeOps storage implementation using Turso"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
turso = { workspace = true }
rootcause = { workspace = true }