[package]
name = "coffee-ops-web"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
coffee-ops-api = {workspace = true}

dioxus = { workspace = true, features = ["router", "fullstack"] }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "coffee-ops-api/server"]
